export default {
    PRODUCTS: "products",
    ADDCART: "addCart",
    MAKECART: "makeCart",
    GETCART: "getCart",
    ADDCONTACTUS: "addContactUs",
    ADDTOCARTMETA: "addCartToMeta",
    GETCARTMETA: "getCartMeta",
    ADDTOSUMMARY: "addToSummary",
    SUMMARY: "getSummary",
    UPDATECARTMETAQUANTITY: "updateCartMetaQuantity",
    DELETECARTMETAITEM: "deleteCartMetaItem",
    UPDATESUMMARY: "updateSummary",
    ADDCARTALERT: "addCartAlert",
    REMOVECARTALERT: "removeCartAlert",
    ADDCHECKOUT: "addCheckout", 
    CUSTOMER: "getCustomer",
    ADDSIGNUP: "addSignUp",
    ADDSIGNIN: "addSignIn",
    ADD_TO_CART: "addToCart",
    REMOVE_FROM_CART: "removeFromCart",
    SIGN_IN: "sign_in",
    CHECK_AUTH: "check_auth",
    UPDATE_CART_STATUS: "updateCartStatus"
};
