export default {
    PRODUCTS: "products",
    ADDCART: "addCart",
    MAKECART: "makeCart",
    GETCART: "getCart",
    ADDCONTACTUS: "addContactUs",
    ADDTOCARTMETA: "addCartToMeta",
    GETCARTMETA: "getCartMeta",
    ADDTOSUMMARY: "addToSummary",
    SUMMARY: "summary",
    UPDATECARTMETAQUANTITY: "updateCartMetaQuantity",
    DELETECARTMETAITEM: "deleteCartMetaItem",
    UPDATESUMMARY: "updateSummary",
    ADDCARTALERT: "addCartAlert",
    REMOVECARTALERT: "removeCartAlert",
    ADDGUESTCHECKOUT: "addGuestCheckout", 
    CUSTOMER: "customer",
    ADDSIGNUP: "addSignUp",
    ADDSIGNIN: "addSignIn",
    ADD_TO_CART: "addToCart",
    REMOVE_FROM_CART: "removeFromCart"
};
